name: Build Program
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore PokemonBWOverlay.sln
 
    - name: Build and Publish Web App
      run: msbuild PokemonBWOverlay.sln /p:Configuration=Release /p:DeployOnBuild=true
 
    - name: Display the path
      run: DIR D:\a\PokemonBWAutoPokedex\PokemonBWAutoPokedex\PokemonBWOverlay
      shell: cmd

    - name: Display the path
      run: DIR D:\a\PokemonBWAutoPokedex\PokemonBWAutoPokedex\PokemonBWOverlay\bin\
      shell: cmd

    - name: Display the path
      run: DIR D:\a\PokemonBWAutoPokedex\PokemonBWAutoPokedex\PokemonBWOverlay\bin\x64\
      shell: cmd

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: PokemonBWOverlay\bin\x64\Release
